# Generated by Django 4.2.3 on 2023-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='description', max_length=1000),
        ),
    ]
