# Generated by Django 4.2.3 on 2023-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apigatewayapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apigatewayname', models.CharField(max_length=100)),
                ('apigatewayaddess', models.CharField(default='description', max_length=1000)),
                ('apigatewaylocation', models.CharField(default='description', max_length=1000)),
            ],
        ),
    ]
