# Generated by Django 4.2.3 on 2023-08-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='engageapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managename', models.CharField(max_length=100)),
                ('manageaddess', models.CharField(default='description', max_length=1000)),
                ('managelocation', models.CharField(default='description', max_length=1000)),
            ],
        ),
    ]
