# Generated by Django 4.2.3 on 2023-08-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('studentaddess', models.CharField(default='description', max_length=1000)),
                ('studentlocation', models.CharField(default='description', max_length=1000)),
            ],
        ),
    ]
