# Generated by Django 4.2.3 on 2023-08-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruit_user_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamename', models.CharField(max_length=100)),
                ('useraddressaddess', models.CharField(default='description', max_length=1000)),
                ('userlocationlocation', models.CharField(default='description', max_length=1000)),
            ],
        ),
    ]
