# Generated by Django 4.2.3 on 2023-08-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payrollapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payrollname', models.CharField(max_length=100)),
                ('payrolladdess', models.CharField(default='description', max_length=1000)),
                ('payrollocation', models.CharField(default='description', max_length=1000)),
            ],
        ),
    ]
